### ISSUE TITLE
Failed to find: com.google.android.gms:play-services-wearable:6.5

### ISSUE THREAD

**Issue by skywalkerlw** [googlesamples/android-WatchViewStub#1]
Please let me know how I can deal with following error? I have added https://dl-ssl.google.com/android/repository/addon-play-services-5.xml

![application_build_gradle_-__application__-_watchviewstub_-____documents_project_demo_watchviewstub_](https://cloud.githubusercontent.com/assets/2090084/5425532/c62482d6-8366-11e4-87e4-0b67feee1f98.png)

**Comment by keyboardsurfer** [comment]
The repository at the given location is no longer active.
Wearable dependencies are being served via the Google Repository within the SDK Manager.
