### ISSUE TITLE
Use of qualifier "-round" instead of WatchViewStub?

### ISSUE THREAD

**Issue by seventhmoon** [googlesamples/android-WatchViewStub#2]
Shall we migrate from WatchViewStub as a holder, to becoming using different qualifier (e.g. -round) to keep the layout more sample?

**Comment by codingjeremy** [comment]
You don't want to use WatchViewStub now.

That said, if you have the same basic layout for square and round, I would use BoxInsetLayout ([instructions](https://developer.android.com/training/wearables/ui/layouts.html#same-layout)).

You can then use the -round qualifier for any other values, dimens, etc. differences between round and square.

If you have different layout between round and square, then drop a different layout in the "layout-round", but again, most people just use the BoxInsetLayout. HOpe that clarifies things for you.
